FROM debian:sid-slim

RUN apt-get update; apt-get install -y --no-install-recommends ca-certificates \
    arc-theme \
    curl \
    fonts-symbola \
    gconf-service \
    gconf2 \
    git \
    gnupg \
    gvfs-bin \
    hicolor-icon-theme \
    libasound2 \
    libcanberra-gtk* \
    libcap2 \
    libgl1-mesa-dri \
    libgl1-mesa-glx \
    libgtk-3-0 \
    libnotify4 \
    libnss3 \
    libpango1.0-0 \
    libpulse0 \
    libv4l-0 \
    libx11-xcb1 \
    libxkbfile1 \
    libxss1 \
    libxtst6 \
    python \
    unzip \
    xdg-utils \
    && rm -rf /var/lib/apt/lists/*
