version: '3.1'

services:
    administration:
        image: xigen/php:cli-5
        container_name: administration
        volumes:
         - ~/git/lifesure/www.lifesure.co.uk:/app
         - ./php.ini:/usr/local/etc/php/conf.d/lifesure.ini
        command: nohup php -S 0.0.0.0:80 -t administration/public
        ports:
            - "8180:80"
        environment:
          APPLICATION_ENV: development

    quotes:
        image: xigen/php:cli-5
        container_name: quotes
        volumes:
         - ~/git/lifesure/www.lifesure.co.uk:/app
         - ./php.ini:/usr/local/etc/php/conf.d/lifesure.ini
        command: nohup php -S 0.0.0.0:80 -t quote
        ports:
            - "8181:80"
        environment:
            APPLICATION_ENV: development

    wp:
        image: xigen/php:cli-5
        container_name: wp
        volumes:
           - ~/git/lifesure/www.lifesure.co.uk:/app
           - ./php.ini:/usr/local/etc/php/conf.d/lifesure.ini
        command: nohup php -S 0.0.0.0:80 -t cms
        ports:
            - "8182:80"
    db:
        image: mysql:5.5
        restart: always
        volumes:
            - ~/.docker_data/lifesure/mysql:/var/lib/mysql:rw
            - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
        environment:
            MYSQL_ROOT_PASSWORD: root
