#!/usr/bin/zsh
alias gop='~/bin/gitopen'
alias dstart='~/bin/docker/start'
alias drestart='~/bin/docker/restart'
alias dstop='~/bin/docker/stop'
alias dlogs='~/bin/docker/logs'

alias chromium-blank='~/bin/docker/chromium-blank'
